# Configuration for Yasb (Yet Another Status Bar)
# Author: @denBot
# Last updated: 21/08/2023

# General Bar Configuration Notes:
#   - All bars must be defined in within the `bars` section
#   - Each bar configuration should be defined using a name, e.g. 'yasb-bar', 'my-awesome-bar', etc.
#   - Default bar options can be found at: https://github.com/denBot/yasb/blob/main/src/core/validation/bar.py#L1-L10

# General Widget Configuration Notes:
#   - ALL configured widgets must be defined in within the `widgets` section of this config file
#   - Each widget configuration should be allocated a unique name, e.g. 'my-widget', 'my-custom-clock', etc.
#      >  This makes it easier for you to keep track of your configured widgets and add them to your bar(s)
#   - Each widget should specify a widget `type` - this points to the python class of the widget you are configuring
#      > For example: type: "yasb.clock.ClockWidget"
#   - Each widget supports mouse event callback functionality (left, middle, right click).
#      > The callbacks "do_nothing" and "exec" can be used across any widget which allows them.
#      > "exec" allows you to run programs from the command-line, where each argument is separated by a space
#      > "do_nothing" allows you to override default mouse events to do nothing
#      > "toggle_label" *some widgets* allow you to toggle between two label formats
#   - Example callbacks:
#      on_left: "exec wt.exe"  --  run the windows terminal when the widget is left-clicked
#      on_middle: "do_nothing" -- overrides default widget middle-click behaviour to do nothing
#      on_right: "exec cmd /c Taskmg" --  open the task manager when the widget is right-clicked


# bars:
# ^ a list of your bar configurations
    # yasb-bar:
    # ^ the name of your bar
       # enabled: true
       # ^ Specify if the bar configuration should be loaded by yasb
       # screens: ['*']
       # ^ A list of screen names which the bar should be displayed on
         # Accepts: a list of screen names
         # Example: [ "\\.\DISPLAY1", "eDP-1", "HDMI-1" ]
         # Wildcard '*' is used to show the bar on all screens
       # class_name: 'yab-bar'
       # ^ The CSS class name used to style the bar and all of its children (widgets).
       # alignment:
       # ^ alignment options are configured here
         # position: 'top' or 'bottom'
         # ^ The vertical positioning of the bar on the screen
         # center: false
         # ^ Specify if the bar should be horizontally centered on the screen.
       # window_flags:
       # ^ special window flags can be enabled here
         # always_on_top: false
         # ^ Forces all windows of lower window levels underneath the bar (even in full-screen).
         # windows_app_bar: false
         # ^ Exclusively reserve the desktop workspace area behind the bar, just like the Windows Taskbar.
      # dimensions:
      # ^ the dimensions of the bar can be set here
        # width: "100%"
        # ^ The width of the bar (in percentage or pixels). Accepts: string (percentage) or positive integer (pixels)        # height: 30
        # ^ The height of the bar (in pixels). Accepts: positive integer (pixels e.g. 20)
      # offset:
        # x: 0
        # ^ The x-axis positioning offset of the bar. Accepts: integer
        # y: 0
        # ^ The y-axis positioning offset of the bar. Accepts: integer
      # widgets:
        # left: []
        # ^ A list of widget names to be placed on the left side of the bar. Accepts: list of strings (widget names / types)
        # center: []
        # ^ A list of widget names to be placed at the center of the bar. Accepts: list of strings (widget names / types)
        # right: []
        # ^ A list of widget names to be placed on the right side of the bar. Accepts: list of strings (widget names / types)

watch_stylesheet: true
watch_config: true

bars:
  yasb-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 20
    padding:
      top: -8
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:   ["komorebi_workspaces", "komorebi_active_layout"]
      center: []
      right:  ["clock"]

widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: "now"
      max_length: 48
      max_length_ellipsis: "..."
      monitor_exclusive: true

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      time_remaining_natural: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
        label: "{%H:%M:%S %Z}"
        label_alt: "{%d-%m-%y %H:%M:%S %Z}"
        timezones: ["Europe/Paris"]
        callbacks:
          on_middle: "exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"
          on_right: "next_timezone"

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "\uf200 {info[histograms][cpu_percent]}"
      label_alt: "\uf200 CPU: {info[percent][total]}% | freq: {info[freq][current]:.2f} Mhz"
      update_interval: 500
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 10

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
        label: "\uf538 {virtual_mem_free}"
        label_alt: "\uf538 {virtual_mem_percent}%"
        update_interval: 5000
        callbacks:
          on_right: "exec cmd /c Taskmgr"

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "Komorebi Offline"
        label_workspace_btn: "{index}"
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: false
      label: "{icon}"
      layout_icons:
        bsp: "[\\\\]"
        columns: "[||]"
        rows: "[==]"
        vertical_stack: "[V]="
        horizontal_stack: "[H]="
        ultrawide_vertical_stack: "||="
        monocle: "[M]"
        maximised: "[X]"
        floating: "><>"
        paused: "[P]"
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_monocle'
        on_right: 'prev_layout'

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
        label: "{wifi_icon}"
        label_alt: "{wifi_icon} {wifi_name}"
        update_interval: 5000
        wifi_icons:
          - "\udb82\udd2e"  # 0% strength (no wifi)
          - "\udb82\udd1f"  # 1-25% strength
          - "\udb82\udd22"  # 26-50% strength
          - "\udb82\udd25"  # 51-75% strength
          - "\udb82\udd28"  # 76-100% strength. Alternate theming: \uf1eb
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec cmd.exe /c start ms-settings:network"
